# (c) Copyright 2021 Christian Saide
# SPDX-License-Identifier: GPL-3.0

name: push

on:
  push:
    branches: [ develop, main ]

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dist/docker/riftdb/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            BUILD=release
          push: true
          tags: |
            ghcr.io/csaide/riftdb:${{ github.sha }}
            ghcr.io/csaide/riftdb:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
